[project]
name = "energy-display"
revision = "1.0"

[profiles.default]
WIFI_SSID = { description = "Name of the Wi-Fi network", required = true }
WIFI_PASSWORD = { description = "Password for the Wi-Fi network", required = true }
MQTT_PASSWORD = { description = "Password for the MQTT broker", required = true }
