[package]
name = "dashboard-core"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
publish = false

[dependencies]
cosmic-text = { version = "=0.19.0", default-features = false, features = ["no_std", "swash"] }
embedded-graphics = "=0.8.2"
heapless = "=0.8.0"
num-traits = { version = "=0.2.19", default-features = false }
serde = { version = "=1.0.229", default-features = false, features = ["derive"] }
serde-json-core = "=0.6.0"
