[env]
ESP_HAL_CONFIG_ENSURE_MAIN_STACK_MINIMUM = "57344"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --partition-table firmware/partitions.csv --monitor"
linker = "xtensa-esp32s3-elf-gcc"
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",
  "-C",
  "link-arg=-Wl,--no-warn-rwx-segments",
]
